### ISSUE TITLE
Task exception was never retrieved (getaddrinfo failed)

### ISSUE THREAD

**Issue by Sparko75** [QiCuiHub/discord-audio-pipe#11]
Hi, when I run dap I can select the device, the server and the channel. The bot can connect to the server but it is muted and cannot transmit any sounds. It leaves automatically after few minutes.

DAP_errors :

Task exception was never retrieved
future: <Task finished coro=<VoiceClient._create_socket() done, defined at site-packages\discord\voice_client.py:172> exception=gaierror(11001, 'getaddrinfo failed')>
Traceback (most recent call last):
  File "site-packages\discord\voice_client.py", line 191, in _create_socket
socket.gaierror: [Errno 11001] getaddrinfo failed
Error on change_channel
Traceback (most recent call last):
  File "ui.py", line 104, in change_channel
    self.voice = await channel.connect()
  File "site-packages\discord\abc.py", line 1080, in connect
  File "site-packages\discord\voice_client.py", line 218, in connect
  File "site-packages\discord\voice_client.py", line 154, in start_handshake
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by Sparko75** [comment]
I tried it on different computers and got the same issue

**Comment by QiCuiHub** [comment]
Thanks for the report, looks like discord changed something behind the scenes and it broke something in the library. https://github.com/Rapptz/discord.py/issues/5191. 

It doesn't seem to be affecting everyone so discord.py is planning to release the fix in their upcoming 1.4 update.
To fix it quickly you could grab the development version of discord.py using git
```
$ git clone https://github.com/Rapptz/discord.py
$ cd discord.py
$ python3 -m pip install -U .[voice]
```

**Comment by Sparko75** [comment]
Thanks for the reply, I did that but nothing changed, guess I have to wait for the update ?

**Comment by QiCuiHub** [comment]
The issue only happens with certain server regions, e.g. Japan.  You could try and find one that gives you the lowest latency, US-Central works for me.

**Comment by Sparko75** [comment]
I tested it again today and it works fine on EUR servers.

**Comment by QiCuiHub** [comment]
Discord v1.4
