### ISSUE TITLE
can't start on debian 10 os

### ISSUE THREAD

**Issue by Suyuimo** [QiCuiHub/discord-audio-pipe#13]
When I start main.pyw a file called "DAP_errors.log" is generated.

This file contains this text:

Error on main
Traceback (most recent call last):
  File "main.pyw", line 27, in <module>
    bot_ui = ui.UI(bot)
  File "/home/server/kiko1/ui.py", line 27, in __init__
    self.device = tk.OptionMenu(self.root, self.dv, *device_options)
TypeError: __init__() missing 1 required positional argument: 'value'

**Comment by QiCuiHub** [comment]
Thanks for reporting this issue, I think this is because the program was not able to detect any valid audio devices. 

Can you post the output from running these commands:
`python -c 'import sounddevice; print(sounddevice.query_hostapis())'`
`python -c 'import sounddevice; print(sounddevice.query_devices())'`

**Comment by Suyuimo** [comment]
Sure here is the output for the two commands:

python -c 'import sounddevice; print(sounddevice.query_hostapis())' ->

root@kiko:/home/server/kiko1# python -c 'import sounddevice; print(sounddevice.query_hostapis())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sounddevice



python -c 'import sounddevice; print(sounddevice.query_devices())' ->

root@kiko:/home/server/kiko1# python -c 'import sounddevice; print(sounddevice.query_devices())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sounddevice


so the module sounddevice is not loaded but why?

**Comment by QiCuiHub** [comment]
Sorry, I might of given you the wrong commands, try python3 instead
`python3 -c 'import sounddevice; print(sounddevice.query_hostapis())'`
`python3 -c 'import sounddevice; print(sounddevice.query_devices())'`

If that gives the same error then I think it might be an installation issue with sounddevice

**Comment by Suyuimo** [comment]
python3 -c 'import sounddevice; print(sounddevice.query_hostapis())' ->

server@kiko:~/kiko2$ python3 -c 'import sounddevice; print(sounddevice.query_hostapis())'
({'name': 'ALSA', 'devices': [0, 1], 'default_input_device': 1, 'default_output_device': 1}, {'name': 'OSS', 'devices': [], 'default_input_device': -1, 'default_output_device': -1})


python3 -c 'import sounddevice; print(sounddevice.query_devices())' ->


server@kiko:~/kiko2$ python3 -c 'import sounddevice; print(sounddevice.query_devices())'
  0 pulse, ALSA (32 in, 32 out)
* 1 default, ALSA (32 in, 32 out)

**Comment by Suyuimo** [comment]
When i start it with the command python3.7 then I get this output:

python3.7 main.pyw ->

Floating point exception


python3 main.pyw create a DAP_errors.log again.

**Comment by QiCuiHub** [comment]
Ah I see, the program is looking for 2 channel devices, but the only device on your system has 32 channels. I'll have to look into how to connect to ALSA.

**Comment by QiCuiHub** [comment]
I've updated the program so it will detect devices with >2 input channels, I'm think it will still work with 32 input channels, but you might need to use something like pavucontrol to configure your audio setup to get things flowing properly.

**Comment by Suyuimo** [comment]
now I get "Floating point exception "

**Comment by QiCuiHub** [comment]
For the floating point exception, does DAP_errors.log contain any output related to this error?

**Comment by Suyuimo** [comment]
nope i don't have a "DAP_errors.log" this time. The Commands doesn't work for me. If i run it as root. I will get a DAP_errors.log that contains:

` 
Error on main
Traceback (most recent call last):
  File "main.pyw", line 27, in <module>
    bot_ui = ui.UI(bot)
  File "/home/server/kiko1/discord-audio-pipe/ui.py", line 9, in __init__
    self.root = tk.Tk()
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

`

**Comment by QiCuiHub** [comment]
Oh it looks like you don't have a screen configured. This program currently only has a GUI, and a command line / discord interface are things that i'm looking to implement.

**Comment by Suyuimo** [comment]
![IMG_20200908_174730.jpg](https://user-images.githubusercontent.com/25396103/92498829-631aaf80-f1fb-11ea-9eae-72d40478daa3.jpg)

**Comment by QiCuiHub** [comment]
Interesting, is that some cloud provider? Try these commands
`xrandr --dpi 96x96`
`export DISPLAY=:0.0`
`xhost +`

**Comment by QiCuiHub** [comment]
I've added the ability to connect directly from the command line without needing to open the GUI. It looks like the platform you are using lacks the X system that tkinter needs to function.

You can try something like ` python3 ./main.pyw --device <device_id> --channel <channel_id> --token <bot_token>` to connect.
Use ` python3 ./main.pyw -q` and `python3 ./main.pyw -o` to get the IDs for devices and channels.
Hopefully this solves your issue, closing for now.
