### ISSUE TITLE
Occasional voice_client / gateway / poll_event error

### ISSUE THREAD

**Issue by MaxLebled** [QiCuiHub/discord-audio-pipe#15]
```
Disconnected from voice... Reconnecting in 1.73s.
Traceback (most recent call last):
  File "discord\voice_client.py", line 270, in poll_voice_ws
  File "discord\gateway.py", line 828, in poll_event
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4000
Disconnected from voice... Reconnecting in 2.09s.
Traceback (most recent call last):
  File "discord\voice_client.py", line 270, in poll_voice_ws
  File "discord\gateway.py", line 828, in poll_event
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4000
```

I've seen connections to a channel very occasionally failing with this error, figured I should report in case there is an improvement that can be made here. This causes DAP to keep everything greyed out after selecting the channel. Connecting to the account & the server works fine.

I use the standalone executable version.

**Comment by QiCuiHub** [comment]
Hi Max, thanks for reporting this. Disconnects from discord is expected every now and then and cannot be avoided because shards can go down on discord's side. Discord.py should automatically try to reconnect, however if its greyed out too long then that would be something that needs to be fixed. 

Is the UI greyed out forever or for many seconds? You can also try the latest executable 1.9, I remember I fixed a case where the UI could get greyed out forever.

**Comment by MaxLebled** [comment]
The error happened upon channel selection, and the entire UI was still greyed out after a minute. I don't know if it would stick forever, but it seemed like it would. I had to restart DAP.exe to retry. I can't repro it consistently, it just happened 3 times so far. This is with the latest executable.

**Comment by QiCuiHub** [comment]
I reduced the timeout period from 60 seconds down to 10 seconds, that way you can try another channel without having to wait a long time to regain control.

I wasn't able to reproduce `discord.errors.ConnectionClosed`, so I'll keep the issue open for now incase the change does not work for this particular error.

**Comment by QiCuiHub** [comment]
Merge with issue https://github.com/QiCuiHub/discord-audio-pipe/issues/16
