### ISSUE TITLE
DAP Won't Launch

### ISSUE THREAD

**Issue by Pickymarker** [QiCuiHub/discord-audio-pipe#18]
When I launch DAP nothing happens can someone help me

**Comment by QiCuiHub** [comment]
Hi,
Did the program leave a DAP_errors.log when you tried opening it? If so, paste the contents and I'll take a look.

**Comment by Pickymarker** [comment]
No it didn't

**Comment by QiCuiHub** [comment]
Are you launching the program with .exe or .pyw? If you are using .pyw, you will have to install all the dependencies for it to run.

**Comment by Pickymarker** [comment]
I'm using the exe

**Comment by QiCuiHub** [comment]
Sorry, the only thing I can think of that would cause that behavior is 32bit vs 64bit.
DAP.exe is 64 bit only. Otherwise. without an error log there's not much I debug.
