### ISSUE TITLE
DAP won't launch

### ISSUE THREAD

**Issue by SirDrillian** [QiCuiHub/discord-audio-pipe#19]
I've downloaded the DAP.exe and attempted to launch it, but it won't launch (no GUI appears. Program appears to execute as Windows shows the spinning circle on the cursor) or generate an error log.

**Comment by SirDrillian** [comment]
I'm running a 64x bit version of Windows, have attempted running as administrator, removing and re-downloading older versions of DAP.exe (It wouldn't work with 20, 1.9a, and 19).

I've attempted allowing it through my firewall (I'm only running windows defender) and running as admin. I experience the same results as before; loading circle appears and nothing appears to run.

**Comment by QiCuiHub** [comment]
Thanks for reporting this issue. Capture cards are something that I haven't considered, and I'll have to look for a resolution. 
The most likely culprit is that I'm using an older version of portaudio that's causing some compatibility issues.

**Comment by SirDrillian** [comment]
Glad I was able to help! I'd be happy to test future iterations when you think you've got a fix for it.
