### ISSUE TITLE
DAP Won't start

### ISSUE THREAD

**Issue by daniellippens** [QiCuiHub/discord-audio-pipe#20]
DAP won't launch and no error log is generated.
I'm on Windows 10 x64. I have all my sound devices disabled except for the Marian Seraph D4 card i'm actually using.
My sound devices are running at 41.100Khz

**Comment by QiCuiHub** [comment]
Thanks for reporting, I've issued a new release that updates some library components.
You can download it here: https://github.com/QiCuiHub/discord-audio-pipe/releases/tag/2.1.
Please try this version and let me know if it solves your issues.

**Comment by daniellippens** [comment]
The update has fixed the issue for me. Thanks for your quick assistance!
