### ISSUE TITLE
Multiple server support.

### ISSUE THREAD

**Issue by devharley** [QiCuiHub/discord-audio-pipe#22]
Heyo! Sorry for using issues as a way to send feedback through.
It seems like multiple server support is possible, but my only workaround is to open a new instance of DAP.
Have you ever thought of having a +1 button to pipe to another server? It's like a Google Forms type where it keeps adding an optional field after the last one was filled.

Opening new instances is adding a new login request to the token, and that's why I'm requesting this feature, so I can have the bot log in once and play on multiple servers as listed.

**Comment by QiCuiHub** [comment]
no problem, this is a good feature to have

**Comment by QiCuiHub** [comment]
https://github.com/QiCuiHub/discord-audio-pipe/releases/tag/2.2
