### ISSUE TITLE
Stuttering Audio in Discord Server Voice Channel

### ISSUE THREAD

**Issue by KoodGarma** [QiCuiHub/discord-audio-pipe#32]
**Describe the bug**
I am able to hear the audio from a music player app such as WinAmp in my Discord server and channel, but it is stuttering.  Here is the audio path I am using: WinAmp -> Voicemeeter VAIO3 Input () -> Voicemeeter Potato A4 -> CABLE-B Input (VB-Audio Cable B) -> Discord Audio Pipe Devices / CABLE-B Output (VB-Audio Cable B)

**To Reproduce**
I tried disconnected and reconnected the DAP.  I also tried different music player apps.

**Expected behavior**
I expect to hear clean, un-stuttering audio in the Discord voice channel.

**Error log**
Paste the contents of DAP_errors.log = ?

**System Info**
 - OS = Windows 10
 - Python or Executable = ?
 - DAP version = dap-2.2-win64

**Additional context**
N/A

**Comment by KoodGarma** [comment]
Fixed it! I changed the Buffering WDM in Voicemeeter Potato from 512 to 1024. No more stuttering!

**Comment by QiCuiHub** [comment]
Good to hear you fixed the issue
