### ISSUE TITLE
Can't get DAP to connect to channel

### ISSUE THREAD

**Issue by TehStoneMan** [QiCuiHub/discord-audio-pipe#33]
Trying to setup DAP for the first time. I run DAP and select the server and channel, the bot comes online, but does not connect.
Running Windows with the .exe (dap-2.2-win64.exe)

Error log:

> 2021-12-13 16:35:53 Error on change_channel
> Traceback (most recent call last):
>   File "gui.py", line 178, in change_channel
>   File "discord\abc.py", line 1154, in connect
>   File "discord\voice_client.py", line 345, in connect
>   File "discord\utils.py", line 350, in sane_wait_for
> concurrent.futures._base.TimeoutError

**Comment by QiCuiHub** [comment]
Maybe a permissions issue, if your channel has custom roles you'll need to check if the bot has the role to the join the channel you want.

**Comment by TehStoneMan** [comment]
OK, thanks. That seems to have fixed it. Is it possible that information can be included in an error message?

**Comment by QiCuiHub** [comment]
Yeah, thanks for posting the log, I'll add additional context for TimeoutError in a next release.
