### ISSUE TITLE
DAP is not working

### ISSUE THREAD

**Issue by Eniuko** [QiCuiHub/discord-audio-pipe#36]
I did everything i had to do, and when I try to turn it on it shows me this:
![image_2022-05-22_180243285](https://user-images.githubusercontent.com/106026590/169704699-2d90e187-6ec7-45c4-9cb8-881db3b53fab.png)

**Comment by QiCuiHub** [comment]
Not quite sure what's happening here. Do you have any additional info like the operating system you're using and was there an errors.log produced?

**Comment by Eniuko** [comment]
I am on widnows 11, and errors.log wasn't produced.

**Comment by QiCuiHub** [comment]
If you just want to get it working you can try installing python and running the source code directly. You can also try running this debug .exe and sharing the error messages here to troubleshoot.

[dap-debug-win64.zip](https://github.com/QiCuiHub/discord-audio-pipe/files/8750407/dap-debug-win64.zip)
