### ISSUE TITLE
Discord Audio Pipe echo

### ISSUE THREAD

**Issue by KoodGarma** [QiCuiHub/discord-audio-pipe#37]
**Describe the bug**
There is an echo of what Discord Audio Pipe is feeding to Discord.

**To Reproduce**
I am able to launch the exe and connect Discord Audio Pipe to my Discord server, but I hear an echo on all the audio that plays thru it when I join the Discord channel to hear other people in it.

**Expected behavior**
No echo on Discord Audio Pipe's feed to Discord.

**Error log**
2022-09-06 21:52:28 Exception in voice thread Thread-3
Traceback (most recent call last):
  File "discord\player.py", line 603, in run
  File "discord\player.py", line 596, in _do_run
  File "discord\voice_client.py", line 638, in send_audio_packet
OSError: [WinError 10038] An operation was attempted on something that is not a socket

**System Info**
 - OS = Windows 10
 - Python or Executable
 - DAP version = dap-2.2-win64

**Additional context**
Other people who join the voice channel do not hear the echo. Only I hear it when I join. Other audio that I play in Discord, like a Youtube link does not have an echo.

**Comment by QiCuiHub** [comment]
Sorry I wasn't able to reproduce this issue on my local machine. I think what's happening here is that you're hearing YouTube and Discord at the same time, and its echoing because Discord has a delay. Maybe another program is picking up on your audio cable output?

**Comment by KoodGarma** [comment]
I FIGURED IT OUT!!! ~ I need to turn the user volume down on the DAP bot when it's in the server's voice channel cause I don't need to hear it when I also log into that voice channel directly. Since I'm already hearing my headphone feed via Voicemeeter Potato, I don't need to also hear the VMP to DAP feed thru Discord.

**Comment by KoodGarma** [comment]
Quick follow up question: Should I increase the voice channel's bitrate? It's currently set at 64kbps but w/ Nitro I can increase it up to 256kbps.

**Comment by QiCuiHub** [comment]
Glad to hear you got it working, as for the bitrate, I don't think the channel bitrate setting has any effect on bots. Bots have their own bitrate, which I think is 128kbps.
