### ISSUE TITLE
DAP wont fully connect

### ISSUE THREAD

**Issue by jmiller15** [QiCuiHub/discord-audio-pipe#39]
I can see the bot in my audio channel but it isn't fully connecting and the mute button the the DAP menu is showing a spinning loading icon.

Other users are able to connect and speak in my channel.
The bot has worked before and I have double checked permissions.
Looks like discord servers are working fine and I also tried toggling between a few region overrides with no success.

log:
2023-03-21 20:16:37 Exception occurred during Voice Protocol voice server update handler
Traceback (most recent call last):
  File "discord\state.py", line 102, in logging_coroutine
  File "discord\voice_client.py", line 295, in on_voice_server_update
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by YourDNDPleasesMe** [comment]
I'm having the same issue. Screenshot below.
![image](https://user-images.githubusercontent.com/87000878/226803608-14d9ee67-0d29-444d-a219-91a232a517c0.png)

I've heard other music bots are having issues today from a discord update. Kenku.fm, for example, had issues today that required an update from the developers:
https://www.reddit.com/r/OwlbearRodeo/comments/11ws9xa/kenku_fm_simply_not_playing_music/
and
https://www.reddit.com/r/OwlbearRodeo/comments/11xwbgo/kenku_fm_not_accepting_token_code/

Thanks for your work on this application. It's my go-to for discord audio sharing, it's simple and fantastic. Please let me know if you have a donation page somewhere!

**Comment by QiCuiHub** [comment]
Thanks! Appreciate the kind words and no donation necessary. What version of dap.exe are you two using? I recently released https://github.com/QiCuiHub/discord-audio-pipe/releases/tag/2.3, to fix a discord breaking change, the 2.2 version no longer works.

**Comment by zack45495** [comment]
Seems Im still getting the spinning mute button/Cant hear audio issue. Looks like yourDNDPleaseMe is on windows. Im on Ubuntu.

Thanks!!

**Comment by QiCuiHub** [comment]
It might be caused by outdated dependencies, try redownloading the source code and update your python dependencies with something like
`pip3 install -r requirements.txt --upgrade`

**Comment by AndrewHopkinson** [comment]
I had the same problem but downloading the latest version 2.3 fixed this issue. However, it only works on my windows 10 machine, not Windows 7, which is what I use to play my audio. :(

**Comment by jmiller15** [comment]
Yes, this is working again with version 2.3

**Comment by AdelKS** [comment]
Hello, it seems that this issue is back again ? Thanks! Or maybe I did not setup the right permissions for the bot ? I have added "Read messages/view channels", "Speak", "Connect"

**Comment by QiCuiHub** [comment]
I wasn't able to reproduce this issue, you might have to check for custom roles in the server, that is common source of problems.

**Comment by AdelKS** [comment]
> you might have to check for custom roles in the server

Thanks ! I removed the custom role given to the bot and it now works. Would be nice to add this information to an FAQ maybe :)

**Comment by AdelKS** [comment]
Actually it looks like it fails to connect if someone is already on the channel :thinking:

**Comment by kiithwarrior** [comment]
> It might be caused by outdated dependencies, try redownloading the source code and update your python dependencies with something like `pip3 install -r requirements.txt --upgrade`

Thanks! This fixed my issue :)

**Comment by DanielTheBard** [comment]
This issue started up for me this week & I have no clue how to solve it. Even when I made a completely new bot, I still have this same exact problem.
