### ISSUE TITLE
Channels with emoji in the name are not filled in the channel list

### ISSUE THREAD

**Issue by Artemia76** [QiCuiHub/discord-audio-pipe#4]
All in the title.

**Comment by QiCuiHub** [comment]
I made some changes so that channels with emojis now show up in the list. Unfortunately tkinter is not able to display emojis so they get replaced with �.

**Comment by Artemia76** [comment]
Nice, that's work! 
Thanks you, I pushed a pullrequest for a nicer "demojify " text

**Comment by QiCuiHub** [comment]
Good idea, I approved the pull request. I modified it a bit so that it still allows things like Kanji or Chinese characters through.
