### ISSUE TITLE
2.3 not working with windows 7?

### ISSUE THREAD

**Issue by AndrewHopkinson** [QiCuiHub/discord-audio-pipe#41]
**Describe the bug**
I was having problems connecting to discord using version 2.2 so I downloaded version 2.3 and it works on my windows 10 machine but not my windows 7 machine.
Message:
THe program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem

I also get another error message 
ERror loading Python DLL
C:\users\temp\appdata\local\...\python310.dll
Loadlibrary: the specified module could not be found

**To Reproduce**
Download version 2.3 into same folder as my token. Double click on the exe

**Expected behavior**
To connect to my discord bot. It works in Windows 10

**Error log**
Paste the contents of DAP_errors.log

**System Info**
 - OS
 - Python or Executable
 - DAP version

**Additional context**

**Comment by QiCuiHub** [comment]
I think windows 7 is not longer supported by python for versions 3.9 and up. 2.3 is built with python 10, so its not going to work with win7. It looks like windows 7 extended support ended on Jan 10, 2023 so I won't be supporting win7, but you can still get it to work by using the source code and running it with python 3.8.
