### ISSUE TITLE
jack support?

### ISSUE THREAD

**Issue by mr-gosh** [QiCuiHub/discord-audio-pipe#6]
Should this be working with [jack](https://jackaudio.org/)?
Cause i only get HDA Intel, pulse and default proposed.

Thanks for helping

**Comment by QiCuiHub** [comment]
I'm not quite sure what might be causing it,
I could be because you started jack after starting the program, because the program only queries devices on startup, or it might be something related to this https://jackaudio.org/faq/pulseaudio_and_jack.html

**Comment by QiCuiHub** [comment]
I managed to get audio from jack into discord after playing around with option 3 and following this thread https://askubuntu.com/questions/572120/how-to-use-jack-and-pulseaudio-alsa-at-the-same-time-on-the-same-audio-device

![image](https://user-images.githubusercontent.com/22136946/82413672-c792e280-9a43-11ea-8feb-50a1f6cf35d2.png)

![image](https://user-images.githubusercontent.com/22136946/82413696-d4173b00-9a43-11ea-8ca6-f2fd3707ab0d.png)

![image](https://user-images.githubusercontent.com/22136946/82413713-da0d1c00-9a43-11ea-9127-9c1230f3d80a.png)

This was done a in VM so i'm not sure if it will translate to your case.
