### ISSUE TITLE
Bot doesn't support stereo audio streaming through discord

### ISSUE THREAD

**Issue by NiklavsD** [QiCuiHub/discord-audio-pipe#7]
The code may support multiple channel transmitting, but discord doesn't.
I've heard there is way around this with discord bots, so I tried with this one, but still didn't work. It was just mono.
I noticed, that "Go live" streaming supports stereo transmission. So that worked, when I tried streaming app and than the app would playback my voice in stereo. Bummer, that others have to join stream, in order to hear that ASMR xD.

**Comment by QiCuiHub** [comment]
Are you using discord in the browser? I've been getting stereo through the standalone discord client but the browser is always in mono.

**Comment by NiklavsD** [comment]
> Are you using discord in the browser? I've been getting stereo through the standalone discord client but the browser is always in mono.

Yes, I was using Discord client. Haven’t tried yet on browser, but as you say, it won’t work.
You have stereo mic? Right? Because I really want to get it work for me also.

**Comment by QiCuiHub** [comment]
I only have a mono mic, but when play things like youtube via virtual audio cable and DAW I get stereo sound. I would have to know a bit more about your setup to troubleshoot the issue.

**Comment by NiklavsD** [comment]
I’m using blue yeti mic, which can be controlled either for mono or stereo.
I have it set on stereo and I’m sure the output of the mic is stereo.
Maybe you can add me, so we can test it tomorrow:
╲⎝⧹ Niklavs ⧸⎠╱#3115

**Comment by QiCuiHub** [comment]
I seems like discord was down for a bit, I've sent you a request as Bittle#7829

**Comment by QiCuiHub** [comment]
Issue was resolved with some setup changes
